<a href="https://colab.research.google.com/github/manuelagutierrezss16/Integraci-n-de-Datos-y-Prospectiva/blob/main/4_1_Integraci%C3%B3n_Multidimencsional_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CASO DE ESTUDIO**

Una entidad prestadora de servicios de salud (EPS) del sistema de
atención en salud en Colombia, requiere mejorar la eficiencia de sus
operaciones del negocio, por lo cual debe reducir su tamaño. (optimización de operaciones integrando diferentes sucursales ubicadas en el Valle de Aburra.)
En este sentido, la EPS quiere centrar sus operaciones en los sectores más cercanos a la ciudad de Medellín por lo que quiere hacer la integración de los pacientes de Coopacabana y Caldas en sus otras sedes. Dentro de los objetivos, quiere evaluar como era la configuración de sus variables para antes y despues de la integracíon de pacientes nuevos.

En este momento vamos a identificar a donde enviar a los pacientes de Caldas y Copacabana teniendo en cienta las siguientes variables:
* Colocar la descripcion de cada una de las variables de trabajo.

0. Cargar librerias

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

1. Se cargan los datos de trabajo

In [27]:
nxl='/content/drive/MyDrive/Colab Notebooks/INTEGRACION/BASES DE DDATOS/5. Diabetes Árbol_Int_Mult.xlsx'
XDB=pd.read_excel (nxl,sheet_name=0)
XDB=XDB.dropna()
XDB.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Numero_Atenciones,Costo_Promedio_Atencion,Ciudad_Pertenencia
0,0,125,96,0,0,22.5,0.262,21,0,4,314.926044,Sabaneta
1,0,141,0,0,0,42.4,0.205,29,1,6,287.355812,Envigado
2,10,101,86,37,0,45.6,1.136,38,1,8,464.541158,Sabaneta
3,1,96,122,0,0,22.4,0.207,27,0,3,368.103292,Sabaneta
4,5,139,64,35,140,28.6,0.411,26,0,9,428.548590,Copacabana

In [28]:
#SE CONSTRUYE LA SEGUNDA BASE DE DATOS (XDB2) PARA CLASIFICAR POR DIABETES Y CIUDAD (la misma base de datos pero lo que necesitamos al final)
XDB2=XDB.iloc[:,[0,1,2,3,4,5,6,7,9,10,8,11]].copy()
display(XDB2)

XDB=XDB.iloc[:,[0,1,2,3,4,5,6,7,9,10]] # Solo están las variables de entrada
display(XDB)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Numero_Atenciones,Costo_Promedio_Atencion,Outcome,Ciudad_Pertenencia
0,0,125,96,0,0,22.5,0.262,21,4,314.926044,0,Sabaneta
1,0,141,0,0,0,42.4,0.205,29,6,287.355812,1,Envigado
2,10,101,86,37,0,45.6,1.136,38,8,464.541158,1,Sabaneta
3,1,96,122,0,0,22.4,0.207,27,3,368.103292,0,Sabaneta
4,5,139,64,35,140,28.6,0.411,26,9,428.548590,0,Copacabana
...,...,...,...,...,...,...,...,...,...,...,...,...
2495,1,118,58,36,94,33.3,0.261,23,3,343.603552,0,Caldas
2496,1,92,62,25,41,19.5,0.482,25,3,94.845893,0,Copacabana
2497,4,123,80,15,176,32.0,0.443,34,7,194.316790,0,Copacabana
2498,5,123,74,40,77,34.1,0.269,28,9,126.343793,0,Sabaneta
2499,10,90,85,32,0,34.9,0.825,56,9,428.137646,1,Sabaneta

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Numero_Atenciones,Costo_Promedio_Atencion
0,0,125,96,0,0,22.5,0.262,21,4,314.926044
1,0,141,0,0,0,42.4,0.205,29,6,287.355812
2,10,101,86,37,0,45.6,1.136,38,8,464.541158
3,1,96,122,0,0,22.4,0.207,27,3,368.103292
4,5,139,64,35,140,28.6,0.411,26,9,428.548590
...,...,...,...,...,...,...,...,...,...,...
2495,1,118,58,36,94,33.3,0.261,23,3,343.603552
2496,1,92,62,25,41,19.5,0.482,25,3,94.845893
2497,4,123,80,15,176,32.0,0.443,34,7,194.316790
2498,5,123,74,40,77,34.1,0.269,28,9,126.343793
2499,10,90,85,32,0,34.9,0.825,56,9,428.137646

2. Se procede con la cración de los clusters para las EPS de los minicipios que van a quedar activos

In [31]:
Xciu= XDB2['Ciudad_Pertenencia'].unique()
Xciu= ['Sabaneta', 'Envigado', 'Medellín', 'Bello'] # Estos serán los concentradores de información
# Se procede con la creación de los clusters
XCm= np.zeros((len(Xciu),10)) # La variable 8 y 11 no se usan porque son variables de salida


# Fase 0 : reconocer los clusters o los valores de entrada por ciudad
for i, city_name in enumerate(Xciu):
  print(i, city_name)
  filas = np.where(XDB2['Ciudad_Pertenencia']==city_name)[0]# Digame las filas en donde dentro de XDB2 cuales son iguales a city name
  XCm[i,:] = np.mean(XDB.iloc[filas,:],axis=0) # axis 0 promedios de columnas

df= pd.DataFrame(XCm,columns=XDB.columns)
df.index=Xciu
display(df)
#

0 Sabaneta
1 Envigado
2 Medellín
3 Bello

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Numero_Atenciones,Costo_Promedio_Atencion
Sabaneta,3.872685,122.824074,67.907407,19.967593,77.511574,31.730093,0.491333,33.488426,5.557870,273.684041
Envigado,3.805699,121.207254,68.829016,20.730570,79.409326,32.046114,0.460345,32.525907,5.515544,282.643785
Medellín,3.820862,120.746032,70.287982,20.977324,82.947846,31.569388,0.489918,33.299320,5.421769,273.701485
Bello,4.123874,122.542793,70.085586,20.614865,78.459459,32.285135,0.481115,33.774775,5.574324,280.357432

3. Se procede con la integración de los pacientes de Caldas y Copacabana

In [37]:
XCiu2=['Caldas','Copacabana']
XCiu3= [] #Aqui voy a almacenar en que EPS quedaron los pacientes
for k in range (len(XDB2)): #Tiene todas las variables completas
  print(XDB2.iloc[k,11]) # A donde pertenece cada paciente

  if XDB2.iloc[k,11]=='Caldas':# or XDB2.iloc[k,11]=='Copacabana': (para borrar todo elif "antes del else")
    d=np.sum((XCm-XDB.iloc[k,:].values)**2,axis=1) # distancia de cada paciente a cada cluster
    nc=np.argmin(d) # dice a cual pertenece la persona
    print(Xciu[nc])
    XCiu3.append(Xciu[nc])

  elif XDB2.iloc[k,11]=='Copacabana':
    d=np.sum((XCm-XDB.iloc[k,:].values)**2,axis=1) # distancia de cada paciente a cada cluster
    nc=np.argmin(d) # dice a cual pertenece la persona
    print(Xciu[nc])
    XCiu3.append(Xciu[nc])

  else:
       XCiu3.append('--')

XDB2['Transferencia']=XCiu3 # Ahora si revisamos XDB2 hay una nueva variable llamda transferencia
display(XDB2)

Sabaneta
Envigado
Sabaneta
Sabaneta
Copacabana
Envigado
Medellín
Medellín
Sabaneta
Bello
Caldas
Envigado
Medellín
Bello
Caldas
Envigado
Envigado
Copacabana
Sabaneta
Envigado
Medellín
Bello
Sabaneta
Sabaneta
Copacabana
Sabaneta
Caldas
Envigado
Caldas
Envigado
Copacabana
Envigado
Sabaneta
Medellín
Copacabana
Sabaneta
Medellín
Sabaneta
Medellín
Bello
Caldas
Envigado
Medellín
Envigado
Copacabana
Sabaneta
Bello
Bello
Envigado
Envigado
Bello
Envigado
Envigado
Bello
Medellín
Medellín
Envigado
Caldas
Envigado
Copacabana
Envigado
Bello
Envigado
Envigado
Copacabana
Envigado
Medellín
Medellín
Bello
Envigado
Medellín
Copacabana
Sabaneta
Medellín
Copacabana
Medellín
Caldas
Bello
Medellín
Copacabana
Medellín
Caldas
Medellín
Envigado
Caldas
Sabaneta
Bello
Caldas
Envigado
Envigado
Copacabana
Envigado
Medellín
Bello
Envigado
Sabaneta
Envigado
Copacabana
Sabaneta
Sabaneta
Medellín
Sabaneta
Bello
Sabaneta
Caldas
Envigado
Caldas
Envigado
Medellín
Envigado
Sabaneta
Medellín
Medellín
Medellín
Caldas
Bello
Copacabana
Medellín
Sabaneta
Sabaneta
Medellín
Copacabana
Envigado
Caldas
Sabaneta
Medellín
Bello
Caldas
Envigado
Medellín
Envigado
Medellín
Sabaneta
Copacabana
Bello
Caldas
Medellín
Copacabana
Envigado
Copacabana
Envigado
Envigado
Medellín
Sabaneta
Copacabana
Envigado
Copacabana
Sabaneta
Caldas
Sabaneta
Bello
Caldas
Envigado
Copacabana
Sabaneta
Caldas
Sabaneta
Envigado
Copacabana
Envigado
Bello
Caldas
Sabaneta
Medellín
Copacabana
Envigado
Copacabana
Envigado
Caldas
Envigado
Bello
Envigado
Copacabana
Sabaneta
Copacabana
Sabaneta
Copacabana
Envigado
Medellín
Sabaneta
Envigado
Bello
Caldas
Sabaneta
Caldas
Sabaneta
Medellín
Copacabana
Medellín
Medellín
Caldas
Sabaneta
Sabaneta
Envigado
Envigado
Medellín
Sabaneta
Medellín
Sabaneta
Medellín
Bello
Caldas
Sabaneta
Caldas
Envigado
Bello
Copacabana
Envigado
Copacabana
Sabaneta
Copacabana
Envigado
Caldas
Sabaneta
Copacabana
Medellín
Sabaneta
Copacabana
Sabaneta
Medellín
Sabaneta
Sabaneta
Bello
Medellín
Envigado
Sabaneta
Medellín
Bello
Caldas
Sabaneta
Envigado
Medellín
Caldas
Medellín
Sabaneta
Medellín
Copacabana
Sabaneta
Sabaneta
Medellín
Sabaneta
Bello
Copacabana
Envigado
Bello
Copacabana
Medellín
Envigado
Envigado
Caldas
Medellín
Bello
Caldas
Sabaneta
Bello
Medellín
Caldas
Medellín
Caldas
Envigado
Copacabana
Medellín
Envigado
Copacabana
Envigado
Bello
Sabaneta
Sabaneta
Sabaneta
Caldas
Envigado
Caldas
Sabaneta
Caldas
Envigado
Copacabana
Medellín
Sabaneta
Copacabana
Envigado
Bello
Caldas
Sabaneta
Bello
Copacabana
Sabaneta
Bello
Sabaneta
Medellín
Envigado
Copacabana
Sabaneta
Caldas
Envigado
Medellín
Caldas
Sabaneta
Bello
Bello
Copacabana
Sabaneta
Envigado
Bello
Caldas
Sabaneta
Bello
Bello
Copacabana
Medellín
Envigado
Envigado
Medellín
Bello
Bello
Bello
Caldas
Sabaneta
Sabaneta
Caldas
Envigado
Envigado
Medellín
Caldas
Medellín
Bello
Caldas
Sabaneta
Medellín
Bello
Copacabana
Envigado
Medellín
Medellín
Caldas
Medellín
Medellín
Sabaneta
Sabaneta
Medellín
Envigado
Caldas
Envigado
Medellín
Caldas
Sabaneta
Copacabana
Envigado
Envigado
Bello
Copacabana
Envigado
Envigado
Caldas
Envigado
Caldas
Envigado
Bello
Sabaneta
Sabaneta
Sabaneta
Copacabana
Envigado
Bello
Sabaneta
Sabaneta
Bello
Medellín
Medellín
Bello
Bello
Envigado
Medellín
Envigado
Medellín
Copacabana
Medellín
Caldas
Envigado
Medellín
Envigado
Caldas
Sabaneta
Caldas
Sabaneta
Bello
Sabaneta
Caldas
Envigado
Bello
Envigado
Caldas
Envigado
Medellín
Medellín
Caldas
Sabaneta
Caldas
Sabaneta
Sabaneta
Sabaneta
Envigado
Sabaneta
Sabaneta
Bello
Caldas
Medellín
Medellín
Bello
Sabaneta
Bello
Bello
Bello
Medellín
Sabaneta
Envigado
Caldas
Sabaneta
Envigado
Copacabana
Sabaneta
Envigado
Caldas
Envigado
Sabaneta
Sabaneta
Bello
Caldas
Envigado
Envigado
Caldas
Envigado
Caldas
Sabaneta
Copacabana
Envigado
Sabaneta
Envigado
Medellín
Bello
Envigado
Copacabana
Sabaneta
Sabaneta
Medellín
Copacabana
Envigado
Envigado
Copacabana
Medellín
Sabaneta
Sabaneta
Sabaneta
Sabaneta
Copacabana
Envigado
Sabaneta
Copacabana
Medellín
Envigado
Bello
Caldas
Sabaneta
Envigado
Bello
Caldas
Envigado
Caldas
Envigado
Bello
Copacabana
Envigado
Caldas
Envigado
Bello
Sabaneta
Sabaneta
Envigado
Sabaneta
Medellín
Copacabana
Medellín
Copacabana
Envigado
Copacabana
Medellín
Bello
Medellín
Medellín
Envigado
Caldas
Envigado
Sabaneta
Envigado
Caldas
Medellín
Caldas
Envigado
Sabaneta
Sabaneta
Caldas
Sabaneta
Copacabana
Envigado
Medellín
Copacabana
Sabaneta
Medellín
Caldas
Sabaneta
Medellín
Caldas
Envigado
Copacabana
Sabaneta
Sabaneta
Envigado
Medellín
Sabaneta
Bello
Sabaneta
Sabaneta
Caldas
Envigado
Envigado
Bello
Bello
Medellín
Bello
Copacabana
Sabaneta
Caldas
Sabaneta
Bello
Envigado
Sabaneta
Envigado
Caldas
Sabaneta
Medellín
Copacabana
Envigado
Envigado
Sabaneta
Copacabana
Envigado
Bello
Envigado
Sabaneta
Medellín
Bello
Medellín
Bello
Sabaneta
Sabaneta
Sabaneta
Medellín
Envigado
Caldas
Sabaneta
Medellín
Envigado
Sabaneta
Sabaneta
Copacabana
Medellín
Caldas
Envigado
Caldas
Sabaneta
Medellín
Bello
Caldas
Medellín
Envigado
Caldas
Envigado
Caldas
Bello
Bello
Envigado
Sabaneta
Bello
Bello
Medellín
Envigado
Envigado
Bello
Caldas
Envigado
Medellín
Caldas
Sabaneta
Sabaneta
Sabaneta
Medellín
Copacabana
Medellín
Medellín
Sabaneta
Envigado
Envigado
Caldas
Envigado
Caldas
Sabaneta
Sabaneta
Bello
Envigado
Copacabana
Envigado
Bello
Sabaneta
Copacabana
Envigado
Bello
Caldas
Envigado
Copacabana
Medellín
Bello
Sabaneta
Envigado
Caldas
Envigado
Sabaneta
Bello
Envigado
Envigado
Bello
Medellín
Copacabana
Sabaneta
Copacabana
Envigado
Bello
Caldas
Sabaneta
Bello
Bello
Caldas
Envigado
Medellín
Envigado
Envigado
Medellín
Caldas
Medellín
Caldas
Sabaneta
Caldas
Envigado
Bello
Sabaneta
Sabaneta
Copacabana
Sabaneta
Caldas
Envigado
Caldas
Sabaneta
Medellín
Bello
Medellín
Medellín
Copacabana
Bello
Caldas
Medellín
Envigado
Bello
Copacabana
Envigado
Caldas
Medellín
Medellín
Medellín
Sabaneta
Sabaneta
Copacabana
Medellín
Bello
Copacabana
Sabaneta
Bello
Copacabana
Bello
Copacabana
Envigado
Bello
Envigado
Sabaneta
Bello
Sabaneta
Sabaneta
Medellín
Sabaneta
Sabaneta
Bello
Copacabana
Envigado
Medellín
Medellín
Copacabana
Medellín
Medellín
Caldas
Envigado
Bello
Caldas
Medellín
Bello
Bello
Medellín
Sabaneta
Medellín
Copacabana
Envigado
Caldas
Sabaneta
Sabaneta
Bello
Medellín
Caldas
Medellín
Medellín
Medellín
Sabaneta
Medellín
Sabaneta
Medellín
Copacabana
Envigado
Envigado
Caldas
Sabaneta
Copacabana
Medellín
Caldas
Envigado
Copacabana
Medellín
Sabaneta
Sabaneta
Copacabana
Envigado
Bello
Sabaneta
Medellín
Medellín
Sabaneta
Bello
Copacabana
Envigado
Sabaneta
Copacabana
Medellín
Caldas
Envigado
Sabaneta
Medellín
Envigado
Sabaneta
Copacabana
Envigado
Sabaneta
Envigado
Bello
Copacabana
Medellín
Sabaneta
Caldas
Bello
Sabaneta
Copacabana
Sabaneta
Bello
Envigado
Medellín
Envigado
Envigado
Medellín
Bello
Caldas
Envigado
Bello
Caldas
Medellín
Sabaneta
Medellín
Bello
Sabaneta
Caldas
Sabaneta
Envigado
Caldas
Sabaneta
Medellín
Bello
Copacabana
Envigado
Medellín
Medellín
Medellín
Medellín
Bello
Caldas
Envigado
Medellín
Copacabana
Envigado
Medellín
Copacabana
Medellín
Envigado
Medellín
Bello
Copacabana
Medellín
Caldas
Envigado
Copacabana
Medellín
Sabaneta
Envigado
Bello
Copacabana
Sabaneta
Medellín
Envigado
Caldas
Sabaneta
Bello
Medellín
Envigado
Sabaneta
Bello
Bello
Sabaneta
Copacabana
Sabaneta
Bello
Copacabana
Medellín
Envigado
Medellín
Envigado
Bello
Medellín
Sabaneta
Sabaneta
Copacabana
Sabaneta
Envigado
Bello
Caldas
Envigado
Copacabana
Envigado
Sabaneta
Bello
Caldas
Sabaneta
Sabaneta
Bello
Bello
Bello
Medellín
Envigado
Bello
Copacabana
Medellín
Envigado
Medellín
Medellín
Sabaneta
Caldas
Sabaneta
Medellín
Caldas
Envigado
Bello
Sabaneta
Caldas
Medellín
Caldas
Bello
Sabaneta
Caldas
Medellín
Medellín
Medellín
Caldas
Envigado
Caldas
Medellín
Bello
Caldas
Bello
Medellín
Medellín
Caldas
Envigado
Copacabana
Medellín
Copacabana
Envigado
Envigado
Caldas
Envigado
Caldas
Medellín
Sabaneta
Sabaneta
Copacabana
Sabaneta
Copacabana
Envigado
Bello
Caldas
Sabaneta
Bello
Envigado
Medellín
Caldas
Sabaneta
Medellín
Sabaneta
Sabaneta
Caldas
Envigado
Caldas
Sabaneta
Copacabana
Sabaneta
Caldas
Envigado
Medellín
Bello
Sabaneta
Bello
Caldas
Medellín
Sabaneta
Envigado
Caldas
Envigado
Caldas
Sabaneta
Medellín
Sabaneta
Envigado
Envigado
Envigado
Envigado
Medellín
Copacabana
Envigado
Copacabana
Envigado
Bello
Bello
Bello
Envigado
Medellín
Sabaneta
Envigado
Medellín
Bello
Caldas
Sabaneta
Copacabana
Envigado
Copacabana
Sabaneta
Medellín
Copacabana
Envigado
Medellín
Envigado
Medellín
Copacabana
Envigado
Bello
Envigado
Caldas
Medellín
Sabaneta
Medellín
Envigado
Medellín
Sabaneta
Caldas
Sabaneta
Caldas
Envigado
Sabaneta
Envigado
Envigado
Sabaneta
Bello
Medellín
Bello
Sabaneta
Sabaneta
Medellín
Bello
Sabaneta
Medellín
Copacabana
Envigado
Caldas
Medellín
Envigado
Bello
Caldas
Sabaneta
Medellín
Bello
Medellín
Envigado
Copacabana
Envigado
Envigado
Sabaneta
Bello
Caldas
Envigado
Bello
Caldas
Envigado
Bello
Sabaneta
Caldas
Sabaneta
Medellín
Medellín
Sabaneta
Medellín
Copacabana
Envigado
Caldas
Sabaneta
Medellín
Sabaneta
Sabaneta
Bello
Caldas
Sabaneta
Medellín
Bello
Envigado
Copacabana
Envigado
Copacabana
Sabaneta
Bello
Medellín
Copacabana
Sabaneta
Caldas
Medellín
Medellín
Medellín
Sabaneta
Medellín
Caldas
Medellín
Envigado
Sabaneta
Medellín
Bello
Envigado
Sabaneta
Caldas
Sabaneta
Bello
Bello
Copacabana
Sabaneta
Caldas
Medellín
Medellín
Bello
Medellín
Copacabana
Medellín
Copacabana
Medellín
Bello
Sabaneta
Medellín
Sabaneta
Caldas
Envigado
Medellín
Sabaneta
Sabaneta
Bello
Bello
Envigado
Copacabana
Envigado
Sabaneta
Bello
Bello
Copacabana
Envigado
Envigado
Envigado
Copacabana
Envigado
Bello
Envigado
Bello
Medellín
Sabaneta
Copacabana
Envigado
Envigado
Bello
Bello
Copacabana
Medellín
Copacabana
Envigado
Bello
Caldas
Envigado
Sabaneta
Envigado
Bello
Medellín
Copacabana
Envigado
Caldas
Envigado
Envigado
Sabaneta
Copacabana
Medellín
Medellín
Copacabana
Sabaneta
Medellín
Caldas
Medellín
Copacabana
Envigado
Envigado
Bello
Medellín
Copacabana
Sabaneta
Copacabana
Medellín
Caldas
Medellín
Copacabana
Medellín
Caldas
Medellín
Bello
Envigado
Medellín
Sabaneta
Envigado
Bello
Medellín
Medellín
Sabaneta
Medellín
Caldas
Envigado
Envigado
Sabaneta
Envigado
Caldas
Envigado
Sabaneta
Medellín
Sabaneta
Copacabana
Envigado
Caldas
Sabaneta
Sabaneta
Copacabana
Envigado
Caldas
Medellín
Sabaneta
Copacabana
Envigado
Sabaneta
Medellín
Copacabana
Envigado
Copacabana
Medellín
Copacabana
Envigado
Copacabana
Sabaneta
Caldas
Envigado
Sabaneta
Caldas
Sabaneta
Sabaneta
Bello
Medellín
Sabaneta
Envigado
Medellín
Envigado
Bello
Bello
Copacabana
Envigado
Medellín
Copacabana
Medellín
Medellín
Bello
Copacabana
Sabaneta
Envigado
Envigado
Copacabana
Envigado
Bello
Bello
Copacabana
Medellín
Caldas
Envigado
Caldas
Envigado
Envigado
Envigado
Envigado
Caldas
Sabaneta
Bello
Envigado
Sabaneta
Bello
Caldas
Envigado
Envigado
Sabaneta
Envigado
Medellín
Caldas
Medellín
Sabaneta
Sabaneta
Copacabana
Envigado
Sabaneta
Caldas
Envigado
Bello
Envigado
Copacabana
Medellín
Envigado
Envigado
Bello
Sabaneta
Bello
Copacabana
Envigado
Medellín
Medellín
Sabaneta
Envigado
Caldas
Sabaneta
Caldas
Sabaneta
Envigado
Copacabana
Medellín
Bello
Sabaneta
Sabaneta
Sabaneta
Bello
Envigado
Copacabana
Envigado
Copacabana
Medellín
Sabaneta
Medellín
Caldas
Envigado
Medellín
Caldas
Bello
Bello
Copacabana
Sabaneta
Bello
Sabaneta
Copacabana
Sabaneta
Bello
Medellín
Sabaneta
Copacabana
Sabaneta
Envigado
Medellín
Sabaneta
Sabaneta
Bello
Bello
Medellín
Bello
Sabaneta
Copacabana
Sabaneta
Sabaneta
Sabaneta
Envigado
Caldas
Envigado
Medellín
Bello
Bello
Sabaneta
Sabaneta
Caldas
Sabaneta
Medellín
Caldas
Sabaneta
Envigado
Sabaneta
Medellín
Bello
Caldas
Medellín
Medellín
Bello
Medellín
Envigado
Caldas
Bello
Bello
Caldas
Sabaneta
Caldas
Envigado
Sabaneta
Sabaneta
Envigado
Bello
Envigado
Envigado
Sabaneta
Caldas
Sabaneta
Medellín
Sabaneta
Sabaneta
Caldas
Sabaneta
Envigado
Medellín
Sabaneta
Bello
Bello
Sabaneta
Caldas
Sabaneta
Sabaneta
Copacabana
Envigado
Bello
Sabaneta
Medellín
Sabaneta
Caldas
Envigado
Medellín
Medellín
Envigado
Bello
Caldas
Sabaneta
Envigado
Envigado
Copacabana
Medellín
Envigado
Medellín
Medellín
Medellín
Medellín
Envigado
Envigado
Caldas
Bello
Caldas
Sabaneta
Sabaneta
Caldas
Medellín
Medellín
Bello
Bello
Caldas
Envigado
Copacabana
Envigado
Envigado
Envigado
Bello
Sabaneta
Copacabana
Medellín
Medellín
Caldas
Sabaneta
Medellín
Sabaneta
Envigado
Copacabana
Sabaneta
Sabaneta
Medellín
Sabaneta
Bello
Sabaneta
Caldas
Envigado
Medellín
Medellín
Copacabana
Sabaneta
Copacabana
Medellín
Sabaneta
Copacabana
Envigado
Medellín
Envigado
Caldas
Sabaneta
Bello
Caldas
Sabaneta
Caldas
Envigado
Medellín
Medellín
Copacabana
Medellín
Bello
Medellín
Bello
Envigado
Caldas
Envigado
Envigado
Bello
Envigado
Sabaneta
Sabaneta
Copacabana
Envigado
Caldas
Envigado
Copacabana
Medellín
Medellín
Medellín
Caldas
Envigado
Sabaneta
Bello
Copacabana
Envigado
Caldas
Medellín
Copacabana
Envigado
Envigado
Bello
Caldas
Envigado
Copacabana
Envigado
Bello
Envigado
Caldas
Medellín
Medellín
Envigado
Caldas
Envigado
Medellín
Caldas
Envigado
Caldas
Sabaneta
Medellín
Bello
Bello
Bello
Caldas
Medellín
Bello
Medellín
Caldas
Medellín
Medellín
Sabaneta
Medellín
Medellín
Sabaneta
Copacabana
Envigado
Sabaneta
Bello
Caldas
Envigado
Medellín
Caldas
Sabaneta
Caldas
Medellín
Bello
Sabaneta
Bello
Sabaneta
Caldas
Sabaneta
Envigado
Sabaneta
Bello
Bello
Bello
Medellín
Caldas
Envigado
Sabaneta
Bello
Medellín
Medellín
Sabaneta
Copacabana
Envigado
Medellín
Bello
Copacabana
Medellín
Medellín
Sabaneta
Sabaneta
Envigado
Sabaneta
Caldas
Medellín
Bello
Copacabana
Medellín
Sabaneta
Caldas
Sabaneta
Envigado
Caldas
Medellín
Caldas
Bello
Envigado
Copacabana
Sabaneta
Sabaneta
Sabaneta
Bello
Caldas
Envigado
Caldas
Envigado
Bello
Medellín
Medellín
Caldas
Sabaneta
Envigado
Envigado
Sabaneta
Copacabana
Sabaneta
Copacabana
Envigado
Bello
Bello
Sabaneta
Envigado
Sabaneta
Sabaneta
Caldas
Sabaneta
Bello
Sabaneta
Medellín
Caldas
Envigado
Copacabana
Envigado
Copacabana
Envigado
Medellín
Envigado
Caldas
Envigado
Bello
Caldas
Envigado
Bello
Envigado
Copacabana
Envigado
Bello
Envigado
Copacabana
Sabaneta
Bello
Caldas
Medellín
Sabaneta
Envigado
Caldas
Sabaneta
Envigado
Envigado
Caldas
Medellín
Medellín
Sabaneta
Medellín
Copacabana
Sabaneta
Medellín
Sabaneta
Sabaneta
Copacabana
Sabaneta
Sabaneta
Copacabana
Envigado
Caldas
Envigado
Copacabana
Medellín
Copacabana
Envigado
Medellín
Copacabana
Sabaneta
Copacabana
Envigado
Copacabana
Medellín
Caldas
Envigado
Copacabana
Sabaneta
Medellín
Medellín
Bello
Bello
Copacabana
Envigado
Envigado
Medellín
Sabaneta
Copacabana
Medellín
Medellín
Medellín
Medellín
Copacabana
Sabaneta
Envigado
Bello
Sabaneta
Sabaneta
Bello
Sabaneta
Bello
Envigado
Envigado
Copacabana
Envigado
Bello
Medellín
Caldas
Sabaneta
Bello
Bello
Copacabana
Envigado
Envigado
Caldas
Envigado
Medellín
Medellín
Copacabana
Sabaneta
Sabaneta
Medellín
Medellín
Envigado
Medellín
Envigado
Medellín
Medellín
Copacabana
Envigado
Medellín
Medellín
Caldas
Medellín
Caldas
Sabaneta
Envigado
Sabaneta
Copacabana
Envigado
Envigado
Sabaneta
Envigado
Sabaneta
Bello
Medellín
Sabaneta
Bello
Envigado
Copacabana
Envigado
Medellín
Envigado
Medellín
Copacabana
Medellín
Bello
Medellín
Caldas
Bello
Medellín
Medellín
Bello
Sabaneta
Medellín
Copacabana
Medellín
Caldas
Sabaneta
Caldas
Envigado
Sabaneta
Medellín
Bello
Caldas
Envigado
Medellín
Medellín
Sabaneta
Envigado
Medellín
Bello
Sabaneta
Bello
Envigado
Caldas
Sabaneta
Sabaneta
Sabaneta
Envigado
Envigado
Medellín
Bello
Copacabana
Sabaneta
Envigado
Sabaneta
Sabaneta
Medellín
Sabaneta
Bello
Sabaneta
Envigado
Envigado
Bello
Copacabana
Sabaneta
Medellín
Caldas
Envigado
Envigado
Bello
Copacabana
Envigado
Medellín
Bello
Bello
Sabaneta
Medellín
Caldas
Envigado
Copacabana
Envigado
Bello
Caldas
Envigado
Copacabana
Sabaneta
Envigado
Caldas
Sabaneta
Sabaneta
Sabaneta
Copacabana
Envigado
Envigado
Bello
Sabaneta
Bello
Sabaneta
Envigado
Bello
Medellín
Caldas
Envigado
Copacabana
Sabaneta
Copacabana
Medellín
Copacabana
Sabaneta
Sabaneta
Envigado
Caldas
Envigado
Envigado
Medellín
Medellín
Caldas
Medellín
Caldas
Sabaneta
Sabaneta
Caldas
Sabaneta
Copacabana
Sabaneta
Envigado
Caldas
Envigado
Bello
Bello
Medellín
Sabaneta
Envigado
Medellín
Caldas
Envigado
Caldas
Envigado
Bello
Copacabana
Envigado
Caldas
Sabaneta
Copacabana
Envigado
Copacabana
Medellín
Sabaneta
Copacabana
Medellín
Bello
Bello
Bello
Copacabana
Envigado
Sabaneta
Envigado
Envigado
Sabaneta
Medellín
Medellín
Copacabana
Envigado
Sabaneta
Medellín
Sabaneta
Copacabana
Envigado
Bello
Sabaneta
Envigado
Sabaneta
Medellín
Envigado
Medellín
Bello
Bello
Sabaneta
Envigado
Bello
Caldas
Medellín
Sabaneta
Sabaneta
Medellín
Bello
Bello
Copacabana
Envigado
Sabaneta
Sabaneta
Copacabana
Medellín
Bello
Bello
Bello
Medellín
Bello
Caldas
Sabaneta
Medellín
Copacabana
Medellín
Sabaneta
Copacabana
Envigado
Sabaneta
Caldas
Sabaneta
Caldas
Sabaneta
Bello
Bello
Medellín
Envigado
Bello
Medellín
Envigado
Envigado
Envigado
Copacabana
Medellín
Caldas
Envigado
Bello
Caldas
Envigado
Copacabana
Medellín
Sabaneta
Caldas
Medellín
Copacabana
Envigado
Copacabana
Sabaneta
Medellín
Caldas
Sabaneta
Sabaneta
Caldas
Sabaneta
Envigado
Envigado
Envigado
Bello
Medellín
Bello
Envigado
Envigado
Envigado
Bello
Bello
Envigado
Sabaneta
Medellín
Sabaneta
Medellín
Medellín
Copacabana
Medellín
Caldas
Sabaneta
Medellín
Sabaneta
Sabaneta
Medellín
Medellín
Sabaneta
Medellín
Copacabana
Envigado
Copacabana
Envigado
Sabaneta
Bello
Envigado
Envigado
Bello
Bello
Medellín
Medellín
Medellín
Caldas
Envigado
Envigado
Sabaneta
Bello
Caldas
Medellín
Copacabana
Medellín
Sabaneta
Envigado
Envigado
Bello
Bello
Sabaneta
Medellín
Envigado
Copacabana
Bello
Envigado
Envigado
Copacabana
Envigado
Medellín
Envigado
Bello
Sabaneta
Envigado
Sabaneta
Envigado
Medellín
Copacabana
Sabaneta
Sabaneta
Medellín
Medellín
Bello
Caldas
Sabaneta
Sabaneta
Bello
Sabaneta
Bello
Sabaneta
Copacabana
Envigado
Copacabana
Medellín
Bello
Caldas
Envigado
Envigado
Envigado
Medellín
Bello
Medellín
Bello
Medellín
Copacabana
Medellín
Bello
Sabaneta
Medellín
Envigado
Envigado
Bello
Copacabana
Medellín
Copacabana
Sabaneta
Sabaneta
Caldas
Medellín
Copacabana
Sabaneta
Sabaneta
Medellín
Bello
Envigado
Caldas
Envigado
Envigado
Copacabana
Envigado
Sabaneta
Medellín
Caldas
Envigado
Caldas
Medellín
Bello
Medellín
Bello
Copacabana
Sabaneta
Medellín
Sabaneta
Copacabana
Envigado
Copacabana
Envigado
Bello
Medellín
Caldas
Medellín
Bello
Copacabana
Sabaneta
Envigado
Copacabana
Medellín
Sabaneta
Bello
Envigado
Medellín
Bello
Copacabana
Sabaneta
Copacabana
Envigado
Copacabana
Medellín
Sabaneta
Sabaneta
Medellín
Copacabana
Envigado
Envigado
Medellín
Copacabana
Envigado
Copacabana
Medellín
Medellín
Copacabana
Sabaneta
Sabaneta
Caldas
Medellín
Sabaneta
Medellín
Caldas
Envigado
Caldas
Envigado
Bello
Medellín
Caldas
Sabaneta
Envigado
Envigado
Sabaneta
Caldas
Envigado
Bello
Envigado
Envigado
Copacabana
Medellín
Medellín
Envigado
Copacabana
Sabaneta
Copacabana
Envigado
Caldas
Sabaneta
Bello
Sabaneta
Medellín
Caldas
Sabaneta
Sabaneta
Bello
Sabaneta
Sabaneta
Copacabana
Sabaneta
Copacabana
Medellín
Sabaneta
Copacabana
Envigado
Medellín
Medellín
Medellín
Copacabana
Envigado
Caldas
Envigado
Bello
Sabaneta
Caldas
Medellín
Medellín
Bello
Copacabana
Sabaneta
Copacabana
Medellín
Copacabana
Sabaneta
Medellín
Medellín
Bello
Sabaneta
Caldas
Sabaneta
Bello
Medellín
Copacabana
Sabaneta
Sabaneta
Sabaneta
Bello
Sabaneta
Medellín
Medellín
Sabaneta
Bello
Medellín
Envigado
Envigado
Caldas
Sabaneta
Medellín
Caldas
Envigado
Sabaneta
Envigado
Medellín
Sabaneta
Copacabana
Envigado
Medellín
Sabaneta
Medellín
Caldas
Sabaneta
Caldas
Sabaneta
Medellín
Caldas
Sabaneta
Sabaneta
Sabaneta
Sabaneta
Envigado
Envigado
Copacabana
Envigado
Medellín
Envigado
Sabaneta
Envigado
Copacabana
Medellín
Sabaneta
Sabaneta
Bello
Medellín
Bello
Envigado
Medellín
Sabaneta
Medellín
Caldas
Medellín
Sabaneta
Sabaneta
Sabaneta
Medellín
Bello
Copacabana
Envigado
Bello
Copacabana
Envigado
Caldas
Envigado
Caldas
Medellín
Medellín
Sabaneta
Bello
Medellín
Bello
Medellín
Caldas
Envigado
Bello
Bello
Envigado
Caldas
Envigado
Sabaneta
Caldas
Envigado
Caldas
Medellín
Sabaneta
Bello
Medellín
Caldas
Envigado
Envigado
Bello
Caldas
Envigado
Sabaneta
Caldas
Envigado
Sabaneta
Envigado

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Numero_Atenciones,Costo_Promedio_Atencion,Outcome,Ciudad_Pertenencia,Transferencia
0,0,125,96,0,0,22.5,0.262,21,4,314.926044,0,Sabaneta,--
1,0,141,0,0,0,42.4,0.205,29,6,287.355812,1,Envigado,--
2,10,101,86,37,0,45.6,1.136,38,8,464.541158,1,Sabaneta,--
3,1,96,122,0,0,22.4,0.207,27,3,368.103292,0,Sabaneta,--
4,5,139,64,35,140,28.6,0.411,26,9,428.548590,0,Copacabana,Envigado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,1,118,58,36,94,33.3,0.261,23,3,343.603552,0,Caldas,Envigado
2496,1,92,62,25,41,19.5,0.482,25,3,94.845893,0,Copacabana,Sabaneta
2497,4,123,80,15,176,32.0,0.443,34,7,194.316790,0,Copacabana,Medellín
2498,5,123,74,40,77,34.1,0.269,28,9,126.343793,0,Sabaneta,--
2499,10,90,85,32,0,34.9,0.825,56,9,428.137646,1,Sabaneta,--